version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running pre build commands"
      - apt-get update
      - pip3 install -r AWSCodePipleline/requirements.txt
  build:
    commands:
      - echo "Running build commands"
      - echo Build completed on "date"
      - python -m unittest discover -s my-api
      
artifacts:
  files:
    - '**/*'
  base-directory: AWSCodePipleline